name: Release docker image
env:
  REGISTRY: docker.pkg.github.com
on:
  push:
    branches: [ master ]
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '10 */3 * * *'

jobs:
  prepare_matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    name: Prepare release matrix
    steps:
      - uses: actions/checkout@v2
      - id: set-matrix
        run: |
          MATRIX=$(cat matrix.json)
          echo "matrix=${MATRIX}" >> $GITHUB_OUTPUT

  publish:
    needs:
      - prepare_matrix
    strategy:
      matrix: ${{fromJson(needs.prepare_matrix.outputs.matrix)}}
    name: Build and publish docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set repository prefix env
        run: |
          LOWER_REPO=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')
          echo "REPO_PREFIX=${LOWER_REPO}" >> $GITHUB_ENV
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ github.token }}
          registry: ${{ env.REGISTRY }}
          repository: ${{ env.REPO_PREFIX }}/pgbouncer
          cache_froms: ${{ format('{0}/{1}/pgbouncer', env.REGISTRY, env.REPOSITORY) }}
          tags: ${{ matrix.tag }}
          build_args: VERSION=${{ matrix.tag }}
          tag_with_ref: true
          tag_with_sha: true
      - name: Push to Quay
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.QUAY_BOT_NAME }}
          password: ${{ secrets.QUAY_BOT_TOKEN }}
          registry: quay.io
          repository: kirilldanshin/pgbouncer
          cache_froms: ${{ format('{0}/{1}/pgbouncer', env.REGISTRY, env.REPOSITORY) }}
          tags: ${{ matrix.tag }}
          build_args: VERSION=${{ matrix.tag }}
          tag_with_ref: true
          tag_with_sha: true
